version: '3.4'

services:
  voter.web:
    image: ${DOCKER_REGISTRY-}voterweb
    build:
      context: .
      dockerfile: src/Web/Voter.Web/Dockerfile

  voter.services.userapi:
    image: ${DOCKER_REGISTRY-}voterservicesuserapi
    build:
      context: .
      dockerfile: src/Services/Voter.Services.UserAPI/Dockerfile

