apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  vote-user-api
  labels:
    name:  vote-user-api
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  vote-user-api
    spec:
      containers:
      - image:  purnajith/voterservicesuserapi:20181219121501
        name:  vote-user-api       
        ports:
        - containerPort:  80